require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SptsController do

  # This should return the minimal set of attributes required to create a valid
  # Spt. As you add validations to Spt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SptsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all spts as @spts" do
      spt = Spt.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spts).should eq([spt])
    end
  end

  describe "GET show" do
    it "assigns the requested spt as @spt" do
      spt = Spt.create! valid_attributes
      get :show, {:id => spt.to_param}, valid_session
      assigns(:spt).should eq(spt)
    end
  end

  describe "GET new" do
    it "assigns a new spt as @spt" do
      get :new, {}, valid_session
      assigns(:spt).should be_a_new(Spt)
    end
  end

  describe "GET edit" do
    it "assigns the requested spt as @spt" do
      spt = Spt.create! valid_attributes
      get :edit, {:id => spt.to_param}, valid_session
      assigns(:spt).should eq(spt)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Spt" do
        expect {
          post :create, {:spt => valid_attributes}, valid_session
        }.to change(Spt, :count).by(1)
      end

      it "assigns a newly created spt as @spt" do
        post :create, {:spt => valid_attributes}, valid_session
        assigns(:spt).should be_a(Spt)
        assigns(:spt).should be_persisted
      end

      it "redirects to the created spt" do
        post :create, {:spt => valid_attributes}, valid_session
        response.should redirect_to(Spt.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spt as @spt" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spt.any_instance.stub(:save).and_return(false)
        post :create, {:spt => {  }}, valid_session
        assigns(:spt).should be_a_new(Spt)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spt.any_instance.stub(:save).and_return(false)
        post :create, {:spt => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spt" do
        spt = Spt.create! valid_attributes
        # Assuming there are no other spts in the database, this
        # specifies that the Spt created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Spt.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => spt.to_param, :spt => { "these" => "params" }}, valid_session
      end

      it "assigns the requested spt as @spt" do
        spt = Spt.create! valid_attributes
        put :update, {:id => spt.to_param, :spt => valid_attributes}, valid_session
        assigns(:spt).should eq(spt)
      end

      it "redirects to the spt" do
        spt = Spt.create! valid_attributes
        put :update, {:id => spt.to_param, :spt => valid_attributes}, valid_session
        response.should redirect_to(spt)
      end
    end

    describe "with invalid params" do
      it "assigns the spt as @spt" do
        spt = Spt.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spt.any_instance.stub(:save).and_return(false)
        put :update, {:id => spt.to_param, :spt => {  }}, valid_session
        assigns(:spt).should eq(spt)
      end

      it "re-renders the 'edit' template" do
        spt = Spt.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spt.any_instance.stub(:save).and_return(false)
        put :update, {:id => spt.to_param, :spt => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spt" do
      spt = Spt.create! valid_attributes
      expect {
        delete :destroy, {:id => spt.to_param}, valid_session
      }.to change(Spt, :count).by(-1)
    end

    it "redirects to the spts list" do
      spt = Spt.create! valid_attributes
      delete :destroy, {:id => spt.to_param}, valid_session
      response.should redirect_to(spts_url)
    end
  end

end
